routes/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from database.contas_db import CONTA

login_route = Blueprint('login', __name__)

@login_route.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Pega os dados do formulário
        username = request.form['username']
        password = request.form['password']

        # Verifica se existe uma conta com o login e senha fornecidos
        for conta in CONTA:
            if conta['login'] == username and conta['senha'] == password:
                # Redireciona para a página principal após login bem-sucedido
                return redirect(url_for('principal.principal'))  # Redireciona para a rota 'principal'

        # Se não encontrar a conta, exibe uma mensagem de erro
        flash('Usuário ou senha inválidos, tente novamente!', 'error')

    # Renderiza a página de login novamente caso haja falha no login
    return render_template('login.html')

routes/main.py
from flask import Blueprint, render_template, request,jsonify
from database.inventory_db import INVENTARIO

inventario_route = Blueprint('inventario', __name__)



@inventario_route.route('/')
def listar_inventario():
    # listar itens
    return render_template('inventory.html', inventario = INVENTARIO)



@inventario_route.route('/', methods=['POST'])
def inserir_item_inventario():
    # Inserir dados do item
    data = request.json
    
    # Criar novo item
    novo_item = { 
        "id": len(INVENTARIO) + 1,  # Gera um ID único
        "nome": data['nome'],        # Nome do recurso
        "tipo": data['tipo'],        # Tipo do recurso
    }

    # Adiciona o novo item ao inventário
    INVENTARIO.append(novo_item)

    # Renderiza o template para exibir o item adicionado e o inventário
    return render_template('item_inventario.html', item=novo_item, inventario=INVENTARIO)



@inventario_route.route('/new_item')
def form_new_item():
    # Formulário para cadastrar item
    return render_template('form_new_item.html') 



# @inventario_route.route('/<int:item_id>')
# def detalhe_item(item_id):
#     # detalhar item especifico
#     return render_template('detail_item.html')

@inventario_route.route('/<int:item_id>/edit')
def edit_item(item_id):
   # editar item
    item = None
    for c in INVENTARIO:
        if c['id'] == item_id:
            item = c

    return render_template('form_new_item.html', item = item)

@inventario_route.route('/<int:item_id>/update', methods = ['PUT'])
def atualizar_item(item_id):
    # atualizar item
    item_editado = None
    data = request.json
    for c in INVENTARIO:
        if c['id'] == item_id:
            c['nome'] = data['nome']
            c['tipo'] = data['tipo']
            item_editado = c
    return render_template('item_inventario.html', item = item_editado)

@inventario_route.route('/<int:item_id>/delete', methods= ['DELETE'])
def deletar_item(item_id):
    # deletar item
    global INVENTARIO
    INVENTARIO = [ c for c in INVENTARIO if c['id'] != item_id ]

    return {'deleted': 'ok'}

routes/principal.py
from flask import Blueprint, render_template

principal_route = Blueprint('principal', __name__)

@principal_route.route('/')

def principal():
    return render_template('principal.html')

templates/form_new_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulario Novo item</title>
</head>
<body>
    <form id="resourceForm" 
    class= "c-form" 
        {% if item %}
            action=" {{ url_for('inventario.atualizar_item', item_id= item.id)}}" 

        {% else %}
            action=" {{ url_for('inventario.inserir_item_inventario')}}" 
        {% endif %}

        method= "{% if item %}PUT{% else %}POST{% endif %}"

        {% if item %}
            c-swap = ".item-{{item.id}}"
            
        {% else %}
            c-append = " #lista-itens " 
        {% endif %}

    c-reload-container="true"
        >
        
        <label for="resourceName">Nome do Recurso:</label>
        <input type="text" id="resourceName" name="nome" {% if item %} value = " {{ item.nome }} " {% endif %}  required>

        <label for="resourceType">Tipo de Recurso:</label>

        <select id="resourceType" required name="tipo">
            <option value="equipamento" {% if item and item.tipo == 'equipamento' %}selected{% endif %}>Equipamento</option>
            <option value="veiculo" {% if item and item.tipo == 'veiculo' %}selected{% endif %}>Veículo</option>
            <option value="dispositivo" {% if item and item.tipo == 'dispositivo' %}selected{% endif %}>Dispositivo</option>
        </select>
        

        <button type="submit" >
            {% if item %}Salvar{% else %}Criar{% endif %}
        </button>

        
    </form>
    
</body>
</html>

templates/inventory.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestão de Recursos</title>
    <link rel="stylesheet" href="styles.css">
    <script src=" {{ url_for('static', filename= 'cru.js') }} " ></script>
    <script src="inventoryControl.js" defer></script>
</head>

<body class="dark-theme">

    


    <h2>Lista de Recursos</h2>
    <table class="table">
        <thead>
            <tr>

                <th scope="col" >id</th>
                <th scope="col" >Nome</th>
                <th scope="col" >Tipo</th>

            </tr>
        </thead>

        <tbody id="lista-itens">

        {% for item in inventario %}
            {% include 'item_inventario.html' %}
        {% endfor %} 

        </tbody>
    </table>


</body>

</html>

templates/item_inventario.html
    <tr class="cliente-{{item.id}}">
        <th scope="row"> {{ item.id}}</th>
        <th> {{ item.nome}}</th>
        <th> {{ item.tipo}}</th>
        <td>
            <button class="btn btn-primary" c-get=" {{ url_for('inventario.edit_item', item_id = item.id) }} " c-target= "#conteiner-form-item" 
            >Editar</button>




            <button class="btn btn-danger" 
            c-delete=" {{ url_for('inventario.deletar_item', item_id = item.id) }}   " c-remove-closest= "tr">
            Deletar</button>
        </td>
    
    </tr>




templates/login.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href=" {{ url_for ('static', filename = 'styles/login.css')    }}"
</head>

<body class="dark-theme">
    <div class="login-container">
        <h1>Login</h1>

        <!-- Exibe a mensagem de erro, se existir -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="error-messages">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <form id="loginForm" method="POST">
            <div class="input-group">
                <label for="username">Usuário:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="password">Senha:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit">Entrar</button>
        </form>
    </div>
</body>

</html>

templates/principal.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href=" {{ url_for ('static', filename = 'styles/principal.css')    }}"

</head>

<body class="dark-theme">
    <header>
        <button id="addResourceBtn">Adicionar/Excluir Recursos</button>

        <button onclick="">Ver Inventário</button>

    </header>

    <main>
        <h1> Gestão de Recursos</h1>

        <div class="conteiner-inventario" id="conteiner-form-item" c-container ="{{ url_for ('inventario.form_new_item') }}"></div>

        <div class="conteiner-inventario" c-container ="{{ url_for ('inventario.listar_inventario') }}"></div>

    </main>

    <!-- Área onde o popup será carregado -->
    <div id="popupContainer" class="popup-container" style="display: none;">
        <div class="popup-content" id="popupContent"></div>
    </div>

    <script>
        // Função para carregar adicionar.html dentro da página -- Coloquei aqui pra ficar mais fácil e não precisar mexer no script do popup
        document.getElementById('addResourceBtn').addEventListener('click', function () {
            fetch('adicionar.html')
                .then(response => response.text())
                .then(html => {
                    document.getElementById('popupContent').innerHTML = html;
                    document.getElementById('popupContainer').style.display = 'block';
                    document.body.style.overflow = 'hidden';  // Evitar scroll ao abrir o popup
                });
        });

        // Fechar popup quando clicar fora dele
        document.getElementById('popupContainer').addEventListener('click', function (event) {
            if (event.target === this) {
                this.style.display = 'none';
                document.body.style.overflow = 'auto';  // Restaurar scroll
            }
        });
    </script>
    <script src=" {{ url_for('static', filename= 'javascript/cru.js') }} " ></script>
</body>

</html>